version: '3.1'

services:
  fpm:
    build:
      context: docker/fpm
      dockerfile: Dockerfile
    ports:
    - '9000:9000'
    volumes:
    - ./api:/app
    working_dir: /app

  nginx:
    image: nginx
    working_dir: /app
    ports:
    - '7777:80'
    volumes:
    - ./api:/app
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:5.7.28
    ports:
    - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-api}
      MYSQL_USER: ${MYSQL_USER:-api}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-api}
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
